### ISSUE TITLE
Fehler beim Compilieren

### ISSUE THREAD

**Issue by poulpoulsen** [WolfgangRamos/emacs-26.1-with-imagemagick-7#1]
Hallo,
erst einmal Daumen hoch für die Bereitstellung dieser Version. Emacs ohne Imagemagick auf Windows ist Mi*.
Habe eben versucht zu kompilieren.
Leider scheint es ein Problem mit Signaturen zu geben...
Woran kann das liegen?

Überprüfe Signaturen der Quell-Dateien mit gpg...
    emacs-26.1.tar.xz ... FEHLGESCHLAGEN (Unbekannter öffentlicher Schlüssel E8BCD7866AFCF978)
==> FEHLER: Eine oder mehrere PGP-Signaturen konnten nicht überprüft werden!

Beste Grüße
Poul

PS: Bin kein Programmierer nur technisch interessierter Emacs-Nutzer, der Emacs auch vornehmlich zum Texten und nicht Programmieren nutzt.

**Comment by WolfgangRamos** [comment]
Hallo Poul,
E8BCD7866AFCF978 ist der public key von Nicolas Petton (aktueller emacs maintainer). Wenn ich die Signatur manuell prüfe mit `gpg --verify emacs-26.1.tar.xz.sig emacs-26.1.tar.xz` (nachdem ich den key von Nicolas in meinen keyring importiert habe), klappt die Prüfung. Wenn `makepkg-mingw` die Prüfung danach macht schlägt sie auch bei mir fehl; leider. Ich vermute, dass `makepkg-mingw` seinen eigenen keyring verwendet. Ich weiß aber auch nicht welchen :( Ich werde versuchen es herauszufinden. Vorübergehend lässt sich das Problem umgehen indem man `makepkg-mingw` die Option `--skippgpcheck` mitgibt.

**Comment by poulpoulsen** [comment]
Hallo,
danke für die Info. Folgendes ist jetzt jedoch passiert:
Kompilieren und install läuft durch. ->Gut
Beim Start kommt die Fehlermeldung über fehlende libdbus, dann Abbruch.
Was tun?
Es soll doch ein mingw-build sein, d.h. natives Windows oder?

Beste Grüße
Poul

**Comment by WolfgangRamos** [comment]
Ja, es ist ein nativer Windows Build, aber für die Erfüllung der Abhängigkeiten ist `pacman` zuständig. Hast du das Buildergebnis mit `pacman` installiert, also `pacman -U mingw-w64-x86_64-emacs-26.1-1-any.pkg.tar.xz` ausgeführt oder startest du Emacs direkt aus dem entpackten Archiv? Wenn du nämlich die Installation ausführst sollte dbus mit installiert werden. Du musst dann natürlich Emacs aus dem msys2 installationsverzeichnis starten. Ich habe den Pfad bei mir gerade nicht vor Augen, aber ich meine es war etwas wie `C:\msys64\minw64\bin\emacs.exe`.

**Comment by poulpoulsen** [comment]
Ah, der Trick war über pacman installieren.
Dann ist alles an seinem Platz.
Emacs läuft jetzt nativ! Superb.

**Comment by poulpoulsen** [comment]
Ah, der Trick war über pacman installieren.
Dann ist alles an seinem Platz.
Emacs läuft jetzt nativ! Superb.
